# Generated by Django 5.1.1 on 2024-09-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.TextField(max_length=600)),
                ('estado', models.CharField(choices=[('completo', 'COMPLETO'), ('incompleto', 'INCOMPLETO')], default='incompleto', max_length=20)),
            ],
        ),
    ]
